"""modify urls table

Revision ID: 26a13bcf869b
Revises: 43f71df15b94
Create Date: 2024-07-13 12:03:20.008348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26a13bcf869b'
down_revision: Union[str, None] = '43f71df15b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_urls_short_key', table_name='urls')
    op.drop_column('urls', 'expires_at')
    op.drop_column('urls', 'short_key')
    op.drop_column('urls', 'visit_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('visit_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('urls', sa.Column('short_key', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('urls', sa.Column('expires_at', mysql.DATETIME(), nullable=True))
    op.create_index('ix_urls_short_key', 'urls', ['short_key'], unique=True)
    # ### end Alembic commands ###
