"""modify urls table

Revision ID: 4fe6e952ac01
Revises: 26a13bcf869b
Create Date: 2024-07-13 12:26:43.921148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe6e952ac01'
down_revision: Union[str, None] = '26a13bcf869b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('short_key', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_urls_short_key'), 'urls', ['short_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_short_key'), table_name='urls')
    op.drop_column('urls', 'short_key')
    # ### end Alembic commands ###
