"""add is_activate column

Revision ID: 9ef72859c210
Revises: 0b9c02e8e45a
Create Date: 2024-07-14 11:45:40.279068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ef72859c210'
down_revision: Union[str, None] = '0b9c02e8e45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.alter_column('urls', 'is_activate',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('urls', 'expire_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expire_at', mysql.DATETIME(), nullable=True))
    op.alter_column('urls', 'is_activate',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('urls', 'expires_at')
    # ### end Alembic commands ###
